### ISSUE TITLE
Contribute to Eclipse PDT

### ISSUE THREAD

**Issue by kaloyan-raev** [yannickl88/phpOrganizeImportsPlugin#2]
This plugin is a really nice work! It addresses one of the feature requests we have in Eclipse PDT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=354782

Please, consider contributing this to the Eclipse PDT project. I can provide any guidance you need to go through the contribution process: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

**Comment by gossi** [comment]
Oh yes, please!

**Comment by yannickl88** [comment]
Thanks for the interest guys, really appreciate it. 

To be honest, I'm not sure if my plugin matches the quality to be included in the PDT, it's not the prettiest thing under the hood. I'm not very experienced when it comes to developing eclipse plugins and PDT.

However, I do not mind giving it a try if you have some time to help me submit a patch.

**Comment by kaloyan-raev** [comment]
@yannickl88 There is always a first time to contribute a code change to Eclipse. You don't need to be a an Eclipse guru to do it. You will submit your change to the Gerrit code review system and we, the PDT committers, will give you the necessary guidance to clean it up, if necessary.

The first thing you need to do is to clone the PDT git repository and make a commit with your change. The available URLs of the PDT git repo are listed at the bottom of this page: http://git.eclipse.org/c/pdt/org.eclipse.pdt.git/

Your change should go in the following two plugins:
  - org.eclipse.php.core - for the build participants and utils
  - org.eclipse.php.ui - for the actions

Once you have the commit ready in your local git repository, you have to push it to Gerrit. There are few prerequisites:
1. Create new Eclipse account, if you don't have one yet: https://dev.eclipse.org/site_login/
2. Sign the Contributor License Agreement: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Foundation_Contributor_License_Agreement
3. Setup SSH keys in Gerrit: https://wiki.eclipse.org/Gerrit#SSH_Keys
4. Make sure the commit message of your change follows these rules: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record
5. Create a push configuration to Gerrit: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#via_Gerrit
6. Push :-)

It may look like lots of steps, but most of them are one-time setup. Future pushes will be much easier. Let me know if you have troubles with any of the steps.

**Comment by kaloyan-raev** [comment]
@yannickl88 Did try preparing a patch for PDT? Any help I can provide?

**Comment by yannickl88** [comment]
@kaloyan-raev is there a setup where I can run PDT from a eclipse project? I've having some trouble testing my changes

**Comment by kaloyan-raev** [comment]
@yannickl88 Check this section in the PDT Contribution Guide: https://wiki.eclipse.org/PDT/Contributing#Working_with_PDT_source_code_in_Eclipse

**Comment by yannickl88** [comment]
@kaloyan-raev thanks, that worked. I merged everything but having some trouble pushing my changes; my push is being rejected by gerrit.

```
$ git push gerrit master:master
Counting objects: 196, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (23/23), done.
Writing objects: 100% (32/32), 17.10 KiB | 0 bytes/s, done.
Total 32 (delta 13), reused 0 (delta 0)
remote: Resolving deltas: 100% (13/13)
remote: Branch refs/heads/master:
remote: You are not allowed to perform this operation.
remote: To push into this reference you need 'Push' rights.
remote: User: ydelange
remote: Please read the documentation and contact an administrator
remote: if you feel the configuration is incorrect
remote: Processing changes: refs: 1, done    
To ssh://ydelange@git.eclipse.org:29418/pdt/org.eclipse.pdt
 ! [remote rejected] master -> master (prohibited by Gerrit)
error: failed to push some refs to 'ssh://ydelange@git.eclipse.org:29418/pdt/org.eclipse.pdt'
```
It's probably something obvious I missed. My guess it's the `master:master` I'm trying to push to, but not sure what else to fill in there.

**Comment by kaloyan-raev** [comment]
@yannickl88 You have to push to refs/for/master instead of to refs/heads/master.

Pushing to refs/heads/master means you want to push directly to the master branch. You are not allowed, because you are not a committer.
Pushing to refs/for/master will create a change in Gerrit to be reviewed and merged in the master branch.

**Comment by yannickl88** [comment]
okay, I think I made a review see https://git.eclipse.org/r/#/c/50944/

**Comment by kaloyan-raev** [comment]
Great! We will look at it and will comment directly in the Gerrit change.
Thank you!
